watchlist = {
    # 🔹 Big Tech & AI
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "META",
    "TSLA",
    "NVDA",
    "IBM",
    "ORCL",
    # 🔹 Semiconductors & Hardware
    "INTC",
    "AMD",
    "QCOM",
    "TXN",
    "MRVL",
    "SWKS",
    "ANET",
    "AVGO",
    "KLAC",
    "LRCX",
    # 🔹 Cloud & Cybersecurity
    "CRM",
    "WDAY",
    "DDOG",
    "SNOW",
    "PLTR",
    "PATH",
    "ZS",
    "PANW",
    "NET",
    "CRWD",
    "OKTA",
    # 🔹 Finance & Banking
    "JPM",
    "BAC",
    "C",
    "GS",
    "MS",
    "WFC",
    "AXP",
    "PYPL",
    "SQ",
    "V",
    "MA",
    "INTU",
    "SOFI",
    # 🔹 Healthcare & Biotech
    "JNJ",
    "PFE",
    "MRNA",
    "BNTX",
    "LLY",
    "VRTX",
    "REGN",
    "BIIB",
    "DNA",
    "ILMN",
    "TMO",
    "ISRG",
    "UNH",
    "HCA",
    # 🔹 Energy & Utilities
    "XOM",
    "CVX",
    "OXY",
    "COP",
    "BP",
    "ENPH",
    "FSLR",
    "NEE",
    "DUK",
    # 🔹 Consumer Goods & Retail
    "PG",
    "KO",
    "PEP",
    "MCD",
    "SBUX",
    "NKE",
    "LULU",
    "TGT",
    "WMT",
    "DG",
    # 🔹 Automotive & Transportation
    "F",
    "GM",
    "RIVN",
    "LCID",
    "HMC",
    "TM",
    "NIO",
    "UPS",
    "FDX",
    "DAL",
    "UAL",
    "BA",
    # 🔹 Industrial & Manufacturing
    "DE",
    "HON",
    "GE",
    "MMM",
    "EMR",
    "LMT",
    "RTX",
    "NOC",
    "GD",
    "TSCO",
    # 🔹 Media, Entertainment, & Gaming
    "NFLX",
    "DIS",
    "WBD",
    "TTWO",
    "ATVI",
    "EA",
    "ROKU",
    "PARA",
    # 🔹 Real Estate & REITs
    "SPG",
    "PLD",
    "O",
    "EQR",
    "AVB",
    "AMT",
    "CCI",
    # 🔹 Airlines, Cruises, & Travel
    "AAL",
    "DAL",
    "UAL",
    "LUV",
    "CCL",
    "RCL",
    "NCLH",
    "ABNB",
    "MAR",
    "HLT",
    # 🔹 Major ETFs (Broader Market Tracking)
    "SPY",
    "QQQ",
    "ARKK",
    "VTI",
    "VOO",
    "XLF",
    "XLK",
    "XLE",
    "XLV",
    "XLY",
    "XLC",
    # 🔹 Commodities & Materials
    "GLD",  # Gold ETF
    "SLV",  # Silver ETF
    "USO",  # Oil ETF
    "BHP",  # BHP Group (Mining)
    "RIO",  # Rio Tinto (Metals & Mining)
    "NEM",  # Newmont (Gold Mining)
    "FCX",  # Freeport-McMoRan (Copper & Gold)
    # 🔹 Popular on r/WallStreetBets
    "GME",  # GameStop
    "AMC",  # AMC Entertainment
    "BBBY",  # Bed Bath & Beyond
    "SPCE",  # Virgin Galactic
    "PLTR",  # Palantir Technologies
    "SOFI",  # SoFi Technologies
    "TLRY",  # Tilray
    "MSTR",  # MicroStrategy
    "RKLB",  # Rocket Lab
    "LUNR",  # Intuitive Machines
}

ambiguous_watchlist = {
    "NOW",
    "SO",
    "COST",
    "HD",
    "BE",
    "PLUG",
    "CAT",
    "SPOT",
    "LOW",
    "BIG",
    "ALL",
    "BEST",
    "LOVE",
    "FUN",
    "FAST",
    "RUN",
    "REAL",
    "WORK",
    "FREE",
    "SAVE",
    "RIOT",
    "HOPE",
    "GOOD",
    "LIVE",
    "IDEA",
    "EVER",
    "TRUE",
}
